services:
  tor:
    build: ./tor
    ports:
      - "9050:9050/tcp"
      - "9050:9050/udp"
      - "9051:9051/tcp"
      - "9051:9051/udp"
    volumes:
      - ./tor/torrc:/etc/tor/torrc
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - "8080:8080"
      - "4001:4001"
      - "127.0.0.1:5001:5001"
    volumes:
      - ${IPFS_DIR}/staging:/export
      - ${IPFS_DIR}/data:/data/ipfs
      - ./ipfs-init:/container-init.d
    environment:
      - PRIVATE_PEER_ID=${PRIVATE_PEER_ID}
      - HOSTNAME=${HOSTNAME}
  client:
    build: .
    deploy:
      mode: replicated
      replicas: ${REPLICAS}
    command: ["python", "tor_client.py"]
    environment:
      - HOSTNAME=${HOSTNAME}:${PORT}
      - SECRET=${SECRET}
      - PRIVATE_PEER_ID=${PRIVATE_PEER_ID}
      - WAIT